import type { Metadata } from "next";
import { Lora, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const paragraph = Lora({
  weight: ["400", "500", "600", "700"],
  subsets: ['latin'],
  variable: '--font-paragraph',
})
const heading = Merriweather({
  weight: ["400", "700"],
  subsets: ['latin'],
  variable: '--font-heading',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${paragraph.variable} ${heading.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
